# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kc < Formula
  desc "Human-friendly macOS Keychain CLI"
  homepage "https://github.com/v-gutierrez/kc"
  version "0.3.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/v-gutierrez/kc/releases/download/v0.3.0/kc-darwin-amd64.tar.gz"
    sha256 "562339c62a6096e94423f7b727f361f0c86b196e7f9ed2583a92f1aa38738c20"

    define_method(:install) do
      bin.install "kc"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/v-gutierrez/kc/releases/download/v0.3.0/kc-darwin-arm64.tar.gz"
    sha256 "09f98f54c8f5352b20a441211d23f5cda19dadd1717a6cca7160e6215c65b6f6"

    define_method(:install) do
      bin.install "kc"
    end
  end

  test do
    system "#{bin}/kc", "--version"
  end
end
