.nh
.TH "KC" "1" "Jan 0001" "kc dev" "kc Manual"

.SH NAME
kc-completion - Generate shell completion script


.SH SYNOPSIS
\fBkc completion SHELL [flags]\fP


.SH DESCRIPTION
Generate a completion script for bash, zsh, fish, or powershell.
Output is written to stdout so it can be sourced or redirected.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for completion


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--vault\fP=""
	target vault (overrides active vault)


.SH SEE ALSO
\fBkc(1)\fP
