.nh
.TH "KC" "1" "Jan 0001" "kc dev" "kc Manual"

.SH NAME
kc-config-unset - Drop an override so the default applies again


.SH SYNOPSIS
\fBkc config unset KEY [flags]\fP


.SH DESCRIPTION
Drop an override so the default applies again


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for unset


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--vault\fP=""
	target vault (overrides active vault)


.SH SEE ALSO
\fBkc-config(1)\fP
