.nh
.TH "KC" "1" "Jan 0001" "kc dev" "kc Manual"

.SH NAME
kc-del - Delete a secret from the keychain


.SH SYNOPSIS
\fBkc del KEY [flags]\fP


.SH DESCRIPTION
Removes KEY from the active vault (or --vault).


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for del


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--vault\fP=""
	target vault (overrides active vault)


.SH SEE ALSO
\fBkc(1)\fP
