.nh
.TH "KC" "1" "Jan 0001" "kc dev" "kc Manual"

.SH NAME
kc-export - Export all secrets from a vault as KEY=VALUE lines


.SH SYNOPSIS
\fBkc export [flags]\fP


.SH DESCRIPTION
Export all secrets from a vault as KEY=VALUE lines


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for export

.PP
\fB-o\fP, \fB--output\fP=""
	write output to file instead of stdout


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--vault\fP=""
	target vault (overrides active vault)


.SH SEE ALSO
\fBkc(1)\fP
