.nh
.TH "KC" "1" "Jan 0001" "kc dev" "kc Manual"

.SH NAME
kc-import - Import KEY=VALUE pairs from a .env file into the active vault


.SH SYNOPSIS
\fBkc import FILE [flags]\fP


.SH DESCRIPTION
Import KEY=VALUE pairs from a .env file into the active vault


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for import


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--vault\fP=""
	target vault (overrides active vault)


.SH SEE ALSO
\fBkc(1)\fP
