.nh
.TH "KC" "1" "Jan 0001" "kc dev" "kc Manual"

.SH NAME
kc-inject - Print a single secret value to stdout (no trailing newline)


.SH SYNOPSIS
\fBkc inject --key KEY [flags]\fP


.SH DESCRIPTION
Print a single secret value to stdout (no trailing newline)


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for inject

.PP
\fB--key\fP=""
	secret key to retrieve

.PP
\fB--no-touch-id\fP[=false]
	skip Touch ID authentication for protected keys


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--vault\fP=""
	target vault (overrides active vault)


.SH SEE ALSO
\fBkc(1)\fP
