.nh
.TH "KC" "1" "Jan 0001" "kc dev" "kc Manual"

.SH NAME
kc-init - Print the shell snippet needed to load kc secrets on startup


.SH SYNOPSIS
\fBkc init SHELL [flags]\fP


.SH DESCRIPTION
Print the shell snippet needed to load kc secrets on startup


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for init


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--vault\fP=""
	target vault (overrides active vault)


.SH SEE ALSO
\fBkc(1)\fP
