.nh
.TH "KC" "1" "Jan 0001" "kc dev" "kc Manual"

.SH NAME
kc-migrate - Migrate secrets from an external Keychain service into a kc vault


.SH SYNOPSIS
\fBkc migrate [flags]\fP


.SH DESCRIPTION
Migrate secrets from an external Keychain service into a kc vault


.SH OPTIONS
\fB--from\fP=""
	source Keychain service name to migrate from

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for migrate


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--vault\fP=""
	target vault (overrides active vault)


.SH SEE ALSO
\fBkc(1)\fP
