.nh
.TH "KC" "1" "Jan 0001" "kc dev" "kc Manual"

.SH NAME
kc-protect - Protect existing secrets with Touch ID


.SH SYNOPSIS
\fBkc protect [flags]\fP


.SH DESCRIPTION
Protect existing secrets with Touch ID


.SH OPTIONS
\fB--all\fP[=false]
	protect all secrets in the target vault

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for protect


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--vault\fP=""
	target vault (overrides active vault)


.SH SEE ALSO
\fBkc(1)\fP
