.nh
.TH "KC" "1" "Jan 0001" "kc dev" "kc Manual"

.SH NAME
kc-search - Fuzzy search keys across vaults


.SH SYNOPSIS
\fBkc search QUERY [flags]\fP


.SH DESCRIPTION
Fuzzy search keys across vaults


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for search

.PP
\fB--json\fP[=false]
	output structured JSON

.PP
\fB--show-values\fP[=false]
	include secret values in results


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--vault\fP=""
	target vault (overrides active vault)


.SH SEE ALSO
\fBkc(1)\fP
