.nh
.TH "KC" "1" "Jan 0001" "kc dev" "kc Manual"

.SH NAME
kc-setup - Migrate plaintext shell secrets into kc and install shell init


.SH SYNOPSIS
\fBkc setup [flags]\fP


.SH DESCRIPTION
Migrate plaintext shell secrets into kc and install shell init


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for setup

.PP
\fB-y\fP, \fB--yes\fP[=false]
	apply migration without interactive confirmation


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--vault\fP=""
	target vault (overrides active vault)


.SH SEE ALSO
\fBkc(1)\fP
