.nh
.TH "KC" "1" "Jan 0001" "kc dev" "kc Manual"

.SH NAME
kc-vault-unuse - Remove this directory's vault pin


.SH SYNOPSIS
\fBkc vault unuse [flags]\fP


.SH DESCRIPTION
Remove this directory's vault pin


.SH OPTIONS
\fB--dir\fP=""
	directory to unpin (default: working directory)

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for unuse


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--vault\fP=""
	target vault (overrides active vault)


.SH SEE ALSO
\fBkc-vault(1)\fP
