.nh
.TH "KC" "1" "Jan 0001" "kc dev" "kc Manual"

.SH NAME
kc-vault-restore - Restore a soft-deleted vault


.SH SYNOPSIS
\fBkc vault restore NAME [flags]\fP


.SH DESCRIPTION
Restore a soft-deleted vault


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for restore


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--vault\fP=""
	target vault (overrides active vault)


.SH SEE ALSO
\fBkc-vault(1)\fP
