.nh
.TH "KC" "1" "Jan 0001" "kc dev" "kc Manual"

.SH NAME
kc-vault-list - List all vaults


.SH SYNOPSIS
\fBkc vault list [flags]\fP


.SH DESCRIPTION
List all vaults


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for list


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--vault\fP=""
	target vault (overrides active vault)


.SH SEE ALSO
\fBkc-vault(1)\fP
