.nh
.TH "KC" "1" "Jan 0001" "kc dev" "kc Manual"

.SH NAME
kc-vault-create - Create a new vault


.SH SYNOPSIS
\fBkc vault create NAME [flags]\fP


.SH DESCRIPTION
Create a new vault


.SH OPTIONS
\fB--description\fP=""
	human-readable purpose of the vault

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for create

.PP
\fB--require-protection\fP[=false]
	reject secrets stored without Touch ID protection

.PP
\fB--tag\fP=[]
	tag the vault (repeatable, e.g. --tag env:prod)


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--vault\fP=""
	target vault (overrides active vault)


.SH SEE ALSO
\fBkc-vault(1)\fP
