.nh
.TH "KC" "1" "Jan 0001" "kc dev" "kc Manual"

.SH NAME
kc-vault-which - Explain which vault kc will use here, and why


.SH SYNOPSIS
\fBkc vault which [flags]\fP


.SH DESCRIPTION
Explain which vault kc will use here, and why


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for which


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--vault\fP=""
	target vault (overrides active vault)


.SH SEE ALSO
\fBkc-vault(1)\fP
