.nh
.TH "KC" "1" "Jan 0001" "kc dev" "kc Manual"

.SH NAME
kc-vault-rename - Rename a vault, keys and history included


.SH SYNOPSIS
\fBkc vault rename OLD NEW [flags]\fP


.SH DESCRIPTION
Rename a vault, keys and history included


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for rename


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--vault\fP=""
	target vault (overrides active vault)


.SH SEE ALSO
\fBkc-vault(1)\fP
