.nh
.TH "KC" "1" "Jan 0001" "kc dev" "kc Manual"

.SH NAME
kc-vault-create - Create a new vault


.SH SYNOPSIS
\fBkc vault create NAME [flags]\fP


.SH DESCRIPTION
Create a new vault


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for create


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--vault\fP=""
	target vault (overrides active vault)


.SH SEE ALSO
\fBkc-vault(1)\fP
