.nh
.TH "KC" "1" "Jan 0001" "kc dev" "kc Manual"

.SH NAME
kc-vault-info - Show a vault's metadata


.SH SYNOPSIS
\fBkc vault info [NAME] [flags]\fP


.SH DESCRIPTION
Show a vault's metadata


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for info

.PP
\fB--json\fP[=false]
	output structured JSON


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--vault\fP=""
	target vault (overrides active vault)


.SH SEE ALSO
\fBkc-vault(1)\fP
