.nh
.TH "KC" "1" "Jan 0001" "kc dev" "kc Manual"

.SH NAME
kc-vault-switch - Set the active vault


.SH SYNOPSIS
\fBkc vault switch NAME [flags]\fP


.SH DESCRIPTION
Set the active vault


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for switch


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--vault\fP=""
	target vault (overrides active vault)


.SH SEE ALSO
\fBkc-vault(1)\fP
