.nh
.TH "KC" "1" "Jan 0001" "kc dev" "kc Manual"

.SH NAME
kc-vault - Manage vaults (service groups)


.SH SYNOPSIS
\fBkc vault [flags]\fP


.SH DESCRIPTION
Vaults group secrets under a Keychain service prefix (kc:{name}).


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for vault


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--vault\fP=""
	target vault (overrides active vault)


.SH SEE ALSO
\fBkc(1)\fP, \fBkc-vault-create(1)\fP, \fBkc-vault-list(1)\fP, \fBkc-vault-switch(1)\fP
