.nh
.TH "KC" "1" "Jan 0001" "kc dev" "kc Manual"

.SH NAME
kc - A human-friendly CLI for macOS Keychain


.SH SYNOPSIS
\fBkc [flags]\fP


.SH DESCRIPTION
kc replaces the macOS security command with an intuitive CLI for managing secrets stored in the native Keychain.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for kc

.PP
\fB-i\fP, \fB--interactive\fP[=false]
	launch interactive TUI

.PP
\fB--vault\fP=""
	target vault (overrides active vault)


.SH SEE ALSO
\fBkc-completion(1)\fP, \fBkc-del(1)\fP, \fBkc-env(1)\fP, \fBkc-export(1)\fP, \fBkc-get(1)\fP, \fBkc-import(1)\fP, \fBkc-init(1)\fP, \fBkc-list(1)\fP, \fBkc-migrate(1)\fP, \fBkc-set(1)\fP, \fBkc-setup(1)\fP, \fBkc-vault(1)\fP
